### ISSUE TITLE
Dependencies not included

### ISSUE THREAD

**Issue by TheRealJP** [lare96/luna#12]
Can you push the dependencies to the project? Would save others a lot of time getting set up.
Also is there a way to contact you in order to discuss other features and design?

**Comment by ryleykimmel** [comment]
No one has the raw dependencies -- Luna utilizes [maven](https://maven.apache.org/) for builds

**Comment by TheRealJP** [comment]
Welp, you live and you learn. Cheers mate.

**Comment by lare96** [comment]
Oh wow, I didn't see this. I apologize. As Ryley said Maven should be used for dependencies and if you want to discuss anything just add my Skype lare96.rsps
