### ISSUE TITLE
Remove magic numbers (in item-related contexts)

### ISSUE THREAD

**Issue by PureCS** [lare96/luna#19]
Create a new constructor for item, with signature: `Item(String name, int amount)` which will then use `ItemDefinition#getItem(String name)` to set its ID. This will result in less magic numbers.

edit: i.e. in `plugins/plugin/player/starter_package.scala`

**Comment by lare96** [comment]
nice idea! will also be sure to add to the documentation that a potentially expensive lookup will be performed

**Comment by PureCS** [comment]
You could optimize it by storing them in a hashmap, mapping name->id or something similar. You also want to implement `Object#hashCode()` for item entries to ensure that collisions do not occur (or are minimized).

**Comment by lare96** [comment]
Might run into some issues with name conflicts, for example there are multiple items with names such as "key", "coins", etc.

It's still definitely useful so I'll add the support for it, but in the starter_package plugin I just left documentation stating what each item is

**Comment by ryleykimmel** [comment]
Magic strings aren't really a good solution either, regardless if they directly relate to item definitions.

Integer representations of items in some kind of static singleton container (with descriptive constant names) would be a better solution and will minimize name conflicts.

**Comment by PureCS** [comment]
I agree with that

**Comment by lare96** [comment]
13a8f89cbbcb400fc09aa380d0c57ba7f488fee6
