### ISSUE TITLE
Data structures that hold definitions should be immutable

### ISSUE THREAD

**Issue by lare96** [lare96/luna#20]
https://github.com/lare96/luna/tree/master/src/main/java/io/luna/game/model/def

using mutable arrays/maps doesn't seem like a good way to go about things

a good solution would be to add a static method to those classes called ```setDefinitons```, the parsers would build the collections and the ```setDefinitons``` method would create an immutable copy of them. subsequent invocation attempts once the immutable collection has already been created will result in an IllegalStateException being thrown

```setDefinitons``` should also be synchronized

**Comment by PureCS** [comment]
Could use `ImmutableList` from guava or `Collections.unmodifiableList` from java std lib.

**Comment by lare96** [comment]
ImmutableList is much better so I ended up using that. Originally I had some issues because Guava immutable collections don't permit nulls but I got around it by replacing null slots with a singleton value {commit 7c3a1ebc0ae97ba13b62567382785211305fdb06}
