### ISSUE TITLE
Movement is a bit janky

### ISSUE THREAD

**Issue by lare96** [lare96/luna#22]
Especially running, which just randomly stops even though the run button is on. Also does this weird thing where it steps back a few of your previous steps

I also need to confirm that the run energy algorithm works correctly (which I can't do until running is fixed)

**Comment by ryleykimmel** [comment]
https://github.com/lare96/luna/blob/master/src/main/java/io/luna/game/model/mobile/WalkingQueue.java#L178

The behavior here is wrong. If your current position is your next position, addFirst doesn't end up adding anything into the queue which makes peekLast return null, if it does you need to fill in the queue with your current position.

Though that won't cause your issue, it looks like this is your problem: https://github.com/lare96/luna/blob/master/src/main/java/io/luna/net/msg/in/WalkingMessageReader.java#L42

You need to keep a separate running state for your player and for the queue, if your player is running it will override the ctrl+click run, ctrl+click will only run one path and then you will revert back to walking as long as you don't have your run toggled.

**Comment by lare96** [comment]
Fixed in commit 1034421eb6b6216949eea4d1be98c1e17dbf3677, thanks ry
