### ISSUE TITLE
Mobs don't appear to players

### ISSUE THREAD

**Issue by lare96** [lare96/luna#25]
When testing punishment commands recently, I noticed that mobs don't appear to players despite being in the same region. I haven't debugged or looked into this at all yet, but I assume it has something to do with [this](https://github.com/lare96/luna/blob/7522d6946be40236d9d3133f505b52db368b35da/src/main/java/io/luna/game/model/region/RegionManager.java#L115)

**Comment by ryleykimmel** [comment]
The getSurrounding method I wrote for apollo works correctly, should see if that has any inspiration for you..

**Comment by lare96** [comment]
Yeah I'll take a look at that, although when issue #17 completes it would change the "getSurroundingRegions" method completely regardless so that might fix it as well

**Comment by lare96** [comment]
Wanted to look into this because it was bothering me, and it turns out the region system works perfectly. 

What's causing mobs not to appear is [this line](https://github.com/lare96/luna/blob/master/src/main/java/io/luna/game/model/region/RegionManager.java#L80) because the I haven't started working on the [priority comparator](https://github.com/lare96/luna/blob/master/src/main/java/io/luna/game/model/region/RegionPriorityComparator.java) for staggered updating yet.

If you replace the TreeSet and comparator instance with a normal HashSet, everything works fine. Once I add support for both staggered updating and normal updating modes this will be fixed.

**Comment by lare96** [comment]
So it's still blocked, just by issue #16 now instead of #17

**Comment by lare96** [comment]
(Indirectly) Fixed in 8c7e4b8e6df8952a6c070c8454951115c330ae51
