### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by AshotN** [lare96/luna#40]
I downloaded this repo and I can't compile it

It seems there are files missing

For example

Server.java
`import io.luna.game.model.item.Shop;`

But there is no such file

Same for
Bank.java
`import io.luna.game.model.inter.StaticInventoryInterface;`

**Comment by hlycklama** [comment]
same here

**Comment by TheRealJP** [comment]
Yeah @lare96 didn't bother using a feature branch so we'll just have to wait it out.

**Comment by lare96** [comment]
This will be resolved shortly, sorry for the inconvenience guys!

**Comment by AshotN** [comment]
Alright, im glad you didn't disappear :P very excited to see whats happening
