### ISSUE TITLE
Official Client

### ISSUE THREAD

**Issue by AshotN** [lare96/luna#45]
Luna doesn't have an official client, or even an unofficial one as far as I know. What do you guys use to run alongside the server?

**Comment by TBubba** [comment]
I'm not sure if I'm hogging your thread/issue, but I think that this is kind of related.

But I just found this repository, and as someone not very familiar with Java, or any of the IDEs used with it I think that it would be useful if the repository's description specified the used IDE, RS client etc.
I'm not asking for a tutorial on how to set up any of those, but a short list of tools and programs used alongside the source.

Thanks for reading. And sorry if this is the wrong place to write this, I can create a new issue (or whatever is appropriate).

**Comment by TheRealJP** [comment]
You can use whatever IDE or client you want. The only limitation is the use of the 317 protocol as the packet structures vary between revisions.

I don't think there will ever be an official client since  the client holds (correct me if I'm wrong) trademarked, copyrighted, and patented material.

**Comment by AshotN** [comment]
I understand the cache is copyrighted. But I can't find a 317 Client that's working right now. If we can't allow a download link here we can link to resources who may.

**Comment by lare96** [comment]
I remember writing somewhere (I think on rune-server) that the "official client" for Luna is the same as the one for Asteria 2.0/3.0

@TBubba I definitely agree though, once I get some underlying issues sorted out ill definitely add something like that to the [wiki](https://github.com/lare96/luna/wiki)

**Comment by AshotN** [comment]
I think I had found that on Github but the link was dead

**Comment by lare96** [comment]
I can get another link for you. But once again, you'll need to generate new RSA keys

**Comment by AshotN** [comment]
I'd appreciate the link. Also if there are some instructions for the RSA keys. I'd appreciate it

**Comment by lare96** [comment]
https://www.dropbox.com/s/fbvm4cmn1ivdjfa/client-317.zip?dl=0 instructions for RSA are in the README file, make another issue if you need further help
