### ISSUE TITLE
Client Not Loading Assets

### ISSUE THREAD

**Issue by AshotN** [lare96/luna#46]
![image](https://cloud.githubusercontent.com/assets/1350342/22823084/04b4b262-ef37-11e6-921a-cbe6a5164522.png)

Any ideas?

**Comment by lare96** [comment]
Will look into this right now

**Comment by AshotN** [comment]
Find anything?

**Comment by lare96** [comment]
I haven't been able to figure out why this is happening. Regardless, you can use any 317 client and the issue tracking is primarily for server-related problems.
