### ISSUE TITLE
How do you compile, build, and run this? 

### ISSUE THREAD

**Issue by drewjbartlett** [lare96/luna#47]
I've tried running maven and I've tried javac to compile and both give me build errors. Am I doing something wrong?

**Comment by tlf30** [comment]
I too would like to know this, it would be nice if someone could wrap up a simple tutorial on how to setup and run.

**Comment by lare96** [comment]
Could you elaborate on the errors you're getting?

**Comment by tlf30** [comment]
Hello, I have it figured out. There is just a lack of documentation. I might do a write up of how to do it.

**Comment by lare96** [comment]
Are you referring to the lack of documentation on how to get started using this?

I wouldn't consider Luna stable by any means, which is why I haven't taken the time out to write up a guide on how to run it yet. But either way I'm glad you figured it out

**Comment by tlf30** [comment]
Yes, although, I have been having a hard time finding a client to use. I have found a lot of old clients with a lot of major problems that have not been updated in forever. Which client do you recommend and I will document how to get started with the entire setup.

**Comment by lare96** [comment]
I personally just use the Asteria 2.0 client

**Comment by tlf30** [comment]
Do you know where a working download of it is, having trouble finding one.

**Comment by tlf30** [comment]
or have sources/know where sources are?

**Comment by lare96** [comment]
https://www.dropbox.com/s/znef5gbp93mduas/asteria_client.zip?dl=0

**Comment by tlf30** [comment]
Thanks

**Comment by lare96** [comment]
Alright, closing this issue now
