### ISSUE TITLE
Project structure and plugin system

### ISSUE THREAD

**Issue by Spirithill** [lare96/luna#53]
Hello, hello.

As I mentioned, I've worked on Asteria for a few weeks now. Asteria(V3 base) has most of the combat "hardcoded" into the source and doesn't really utilise the plugin system much. I checked few releases based on Asteria and everything was pretty much crammed into already existing classes, into the source.

That's what I am familiar with, that's what we did back in 2006-2011.

My understanding is that there shouldn't(when finished, of course) be a need for common developer to delve into the Luna source but write everything into the plugins.

So, what I don't understand is: What is the benefit of having skills(experience, levels, factors, combat level)?

If I were to develop my fork, what should I write to the source and what should I write into the plugins?(I am somewhat familiar with plugin model but It seems I cannot apply it to RSPS)

~Spirithill

P.S. Wanted to discuss, but have no idea if "issue" is the appropriate way of doing that on GitHub. I am bew to GitHub, sorry.

**Comment by tlf30** [comment]
Hello @Spirithill, this is a fine way to discuss this. 

I am not entirely sure on what you are asking, but if you need help with anything, let me know and I would love to help. I am still learning the ins and outs of Luna myself, but I am excited that others are interested in working on the project.

**Comment by lare96** [comment]
Closing as discussion is a year old.
