### ISSUE TITLE
Outgoing packet priorities

### ISSUE THREAD

**Issue by lare96** [lare96/luna#69]
Player updating packets should be the first packets sent to the client. Netty does not have any form of message prioritization, so I'll have to think of a creative way to implement it.

**Comment by ryleykimmel** [comment]
Flush only those messages instantly using `writeAndFlush` all others use Netty's build in message batching by only calling `write` and `flush` once per pulse

**Comment by lare96** [comment]
But won't there already be messages in the channel's internal queue from packet handling, which happens before updating?
