### ISSUE TITLE
More complex player rights system

### ISSUE THREAD

**Issue by lare96** [lare96/luna#7]
That can include donators, developers, veterans, etc.

**Comment by Promises** [comment]
Maybe not make it 'right',  but more like an add on status?

**Comment by Promises** [comment]
Rights*

**Comment by lare96** [comment]
Was thinking of that too but at the same time I feel like decoupling the two could get annoying

**Comment by Promises** [comment]
I feel making them 'rights' is damn annoying, as it makes it confusing, comparing moderator rights to a veteran status.

**Comment by lare96** [comment]
right which is why im looking for the perfect compromise in not having them too decoupled where they're separate systems but also not too coupled where you're comparing a donator status to an administrator status

**Comment by Promises** [comment]
You should be able do be both donor and moderator.

**Comment by lare96** [comment]
yeah, the best way to achieve this is to just keep PlayerRights with things that can be compared: player, moderator, admin, developer, super admin, head admin, etc. 

anything else should be loaded somewhere else in the file as "isDonator" or whatever
